### ISSUE TITLE
Assess AWS Quicksight

### ISSUE THREAD

**Issue by davidbridgwood** [moj-analytical-services/tech-radar-demo-test#1]
# Description

Look into AWS Quicksight as a potential BI tool

## To Do:
- [ ] #2
- [ ] work with users to understand their BI needs
- [ ] attempt to connect to data on the platform
- [ ] assess features against user needs
- [ ] write up assessment of work and present back
